### ISSUE TITLE
Add shadow to play button so it's visible on light imgs.

### ISSUE THREAD

**Issue by steve-schultz** [theberrics/html5-skin#3]
x:0;  y:1;  blur: 4;  spread: 0;       opacity: 30%;

**Comment by boxyardboy** [comment]
done

**Comment by boxyardboy** [comment]
@steve-schultz 

Attached is a screenshot of the drop shadow I added to the play button per your request.

![screen shot 2016-07-14 at 11 04 36 am](https://cloud.githubusercontent.com/assets/18294087/16850261/2a50687e-49b3-11e6-9384-63f314fcb5b8.png)

Because that element is a font and not a box object, it doesn't have a "spread" value for the shadow. A text-shadow in CSS has (position-x, position-y, blur, color).

Let me know if you need this adjusted.

Thanks man!!!
